package model;
// Generated 10/04/2016 06:18:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UsrMstr generated by hbm2java
 */
@Entity
@Table(name="usr_mstr"
    ,schema="dbo"
    ,catalog="andi"
)
public class UsrMstr  implements java.io.Serializable {


     private String usrId;
     private String usrName;
     private String usrPass;

    public UsrMstr() {
    }

	
    public UsrMstr(String usrId) {
        this.usrId = usrId;
    }
    public UsrMstr(String usrId, String usrName, String usrPass) {
       this.usrId = usrId;
       this.usrName = usrName;
       this.usrPass = usrPass;
    }
   
     @Id 

    
    @Column(name="usr_id", unique=true, nullable=false, length=50)
    public String getUsrId() {
        return this.usrId;
    }
    
    public void setUsrId(String usrId) {
        this.usrId = usrId;
    }

    
    @Column(name="usr_name", length=50)
    public String getUsrName() {
        return this.usrName;
    }
    
    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }

    
    @Column(name="usr_pass", length=50)
    public String getUsrPass() {
        return this.usrPass;
    }
    
    public void setUsrPass(String usrPass) {
        this.usrPass = usrPass;
    }




}


